name: Merge upstream

on:
  schedule:
    - cron: "0 19 * * 1" # monday at noon
  workflow_dispatch:

concurrency:
  group: merge-upstream-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  merge_upstream:
    uses: SpiralP/github-reusable-workflows/.github/workflows/merge-upstream.yml@main
    with:
      url: https://github.com/binwiederhier/ntfy.git
